apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ingestion-data
  namespace: ingestion
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}