apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-ui-pvc
  namespace: chat-ui
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
