apiVersion: v1
kind: Service
metadata:
  name: chat-ui
  namespace: chat-ui
spec:
  type: {{ .Values.service.type }}
  selector:
    app: chat-ui
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
