apiVersion: v1
kind: Service
metadata:
  name: reranker
  namespace: reranker
spec:
  type: {{ .Values.service.type }}
  selector:
    app: reranker
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
