apiVersion: v1
kind: Service
metadata:
  name: embedding
  namespace: embedding
spec:
  type: {{ .Values.service.type }}
  selector:
    app: embedding
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}